# Generated by Django 3.2.16 on 2023-05-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qty', '0002_targetqty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurement',
            new_name='MeasureQty',
        ),
    ]
