# Generated by Django 3.2.16 on 2023-05-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qty', '0003_rename_measurement_measureqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measureqty',
            name='p_cfd',
        ),
        migrations.AlterField(
            model_name='measureqty',
            name='delta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='measureqty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='measureqty',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='targetqty',
            name='expression',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='targetqty',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='targetqty',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
